### Current user
GET {{baseUrl}}/rest/auth/1/session
User-Agent: IntelliJ (Sven Haberer - DDS)
Authorization: Bearer {{userToken}}

### Search jiraIssues
POST {{baseUrl}}/rest/api/2/search
User-Agent: IntelliJ (Sven Haberer - DDS)
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
    "jql": "updatedDate >= startOfWeek('+1d') and timespent > 0 order by updatedDate asc",
    "fields": [
        "summary",
        "updated"
    ],
    "startAt": 0,
    "maxResults": 1000
}

### Get issue worklogs
# Does not support pagination, although the response looks like it's a paginated response.
GET {{baseUrl}}/rest/api/2/issue/{{issueId}}/worklog
User-Agent: IntelliJ (Sven Haberer - DDS)
Authorization: Bearer {{userToken}}

### Add worklog
POST {{baseUrl}}/rest/api/2/issue/{{issueId}}/worklog?adjustEstimate=leave
User-Agent: IntelliJ (Sven Haberer - DDS)
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
    "comment": "Timera test by Sven Haberer - DDS",
    "started": "2024-11-29T19:00:00.000+0100",
    "timeSpentSeconds": 3600
}

> {%
    client.global.set("worklogId", response.body.id);
%}

### Update worklog
PUT {{baseUrl}}/rest/api/2/issue/{{issueId}}/worklog/{{worklogId}}?adjustEstimate=leave
User-Agent: IntelliJ (Sven Haberer - DDS)
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
    "comment": "Timera test by Sven Haberer - DDS",
    "started": "2024-11-29T20:00:00.000+0100",
    "timeSpentSeconds": 3600
}

### Delete worklog
DELETE {{baseUrl}}/rest/api/2/issue/{{issueId}}/worklog/{{worklogId}}?adjustEstimate=leave
User-Agent: IntelliJ (Sven Haberer - DDS)
Authorization: Bearer {{userToken}}
